### ISSUE TITLE
Errors on Windows XP without message

### ISSUE THREAD

**Issue by msikma** [FrankCYB/JavaGPT#1]
Hi there. I've tried out this program on Windows XP after seeing you posting about it on Reddit.

For some reason it doesn't seem to work for me, and I'm not sure why since the error message doesn't have a reason in it. Here's some screenshots that show what's happening:

<img width="721" alt="Screen Shot 2023-04-07 at 14 51 09" src="https://user-images.githubusercontent.com/1507745/230612098-8a77d9c3-3fc4-4f16-a002-a852c5a5d049.png">

<img width="707" alt="Screen Shot 2023-04-07 at 14 51 32" src="https://user-images.githubusercontent.com/1507745/230612115-b40bf1af-54e4-4c5d-b20b-74fe8e63821b.png">

After the "closed" message box is closed, a "null" response ends up in the output window. I'm running Java 8 update 152 on XP SP3 with all final updates applied.

**Comment by FrankCYB** [comment]
In my Demo, I'm using Java 8u181 as it has better support for TLS 1.2 on Windows XP SP3. However, I just tested Java 8u152 on Windows XP SP3 on v0.10 and I can't replicate the same issue under normal operations. However when I input an invalid apikey the "closed" message box appears. Try resetting your apikey from OpenAI website as its possible your current key is expired. Also check your apikey usage to see if its full ([Link here](https://platform.openai.com/account/usage)). 

Also, I just put out version v1.0.0 which uses a better API code base and patched out a lot of bugs and stability issues present in v0.10. There's many new features added as well which make the user experience much better. I suggest you try out v1.0.0 and report back if there's any issues on your end. Thank you for taking the time to submit your report.
