### ISSUE TITLE
Foreign languages are not supported!

### ISSUE THREAD

**Issue by nimbus2332** [FrankCYB/JavaGPT#3]
![image](https://user-images.githubusercontent.com/54532528/234352287-48304377-7226-4d23-82e0-45ea10208a98.png)

**Comment by FrankCYB** [comment]
I`m currently working on implementing built in Unicode support for JavaGPT. However at the moment there is a work around. If you launch JavaGPT with the argument "-Dfile.encoding=UTF-8" it will display foreign languages properly. 

To do this simply run the command "java -Dfile.encoding=UTF-8 -jar JavaGPT.jar" in the same directory as JavaGPT to launch with Unicode support. You can also automate this by making a .bat file on Windows or .sh on Linux/Mac.

**Comment by FrankCYB** [comment]
I just released a new update (v1.3.0) which adds foreign language support (Unicode). Check [latest releases ](https://github.com/FrankCYB/JavaGPT/releases/latest).

Thank you for your feedback!
