### ISSUE TITLE
JavaGPT.jar not present in ZIP Download

### ISSUE THREAD

**Issue by velliott51** [FrankCYB/JavaGPT#4]

**Comment by FrankCYB** [comment]
Make sure you download the release zip from the releases page and not the source code zip. Only the release zip will contain the compiled JavaGPT jar. Here's a direct link to the current latest Jar of JavaGPT (1.3.1): https://github.com/FrankCYB/JavaGPT/releases/download/v1.3.1/JavaGPT.1.3.1.zip

Newer releases will always be accessible via this URL: https://github.com/FrankCYB/JavaGPT/releases/latest
