### ISSUE TITLE
The proxy configuration in 'config.properties' is not taking effect.

### ISSUE THREAD

**Issue by katohk** [FrankCYB/JavaGPT#5]
I set the proxy in config.properties, but it doesn't seem to take effect. To enable https proxy, I believe it's necessary to set the system properties "https.proxyHost" and "https.proxyPort".

**Comment by FrankCYB** [comment]
If you are using an HTTPS proxy, make sure you set "proxytype=" to "proxytype=HTTPS" in config.properties otherwise it will default to work with SOCKS proxies.

**Comment by katohk** [comment]
I tried setting "proxytype" to "HTTPS," but it didn't have any effect. In the case of HTTPS, I believe you need to set the system properties "https.proxyHost" instead of "http.proxyHost" for the configuration to take effect.

**Comment by FrankCYB** [comment]
You are correct. I have addressed this issue in the latest release (v1.3.2). HTTPS proxies now will initialize and work properly. My apologies for the oversight. 

Latest release: https://github.com/FrankCYB/JavaGPT/releases/latest
